# A dummy app to emulate json request

import requests
import json

URL = "http://127.0.0.1:8000/api/"

def get_data(id = None):
    data = {}
    if id is not None:
        data = {"id" : id}
    
    json_data = json.dumps(data)
    r = requests.get(url = URL, data = json_data)
    # r = requests.get(URL).json()
    data = r
    print(data)

get_data(1)
# Generated by https://quicktype.io


class TopLevel:
    user_id: int
    id: int
    title: str
    completed: bool

    def __init__(self, user_id: int, id: int, title: str, completed: bool) -> None:
        self.user_id = user_id
        self.id = id
        self.title = title
        self.completed = completed
